name: Continuous Integration

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  lint:
    # TODO: Split these into seperate jobs that can run in parallel
    name: CI
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: volta-cli/action@v1
      - uses: pnpm/action-setup@v1.2.1
        with:
          version: 4.11.1
          run_install: |
            - recursive: true
              args: [--frozen-lockfile, --strict-peer-dependencies]
      - name: Build
        run: pnpm build
      - name: Test
        run: pnpm test